---
name: black_science_edu
channels:
  - conda-forge
  - defaults
dependencies:
  - nodejs=9.11.1
  - openssl=1.0.2o
  - pandas=0.22.0
  - planemo>=0.55.0
  - readline=7.0
  - requests=2.18.4
  - ruby=2.4.4
  - yaml=0.1.7
  - yamllint=1.11.0
  - zlib=1.2.11
  - libxml2
  - pkg-config
